### ISSUE TITLE
Bug at npm install

### ISSUE THREAD

**Issue by Ectalite** [EndlessHosting/Discord-LiveBot#16]
Freeze at npm `npm install`:
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:567:12)
npm WARN addRemoteGit  hydrabolt/discord.js#11.3-dev resetting remote /home/xavier/.npm/_git-remotes/git-github-com-hydrabolt-discord-js-git-11-3-dev-58d7434c because of error: { Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:567:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
loadDevDep:discord.js → a ▀ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

**Comment by Uni-Nugiolu** [comment]
Do you have git installed?

**Comment by Ectalite** [comment]
I use ‘git clone ... ‘ everytime

**Comment by codepupper** [comment]
Have you tried using the Dev branch?

**Comment by Ectalite** [comment]
I didn‘t, I only tested the master branch. Will test it

**Comment by Ectalite** [comment]
The dev branch works actually, but why does it not work on the master branch ?

**Comment by codepupper** [comment]
I personally actually don't know. @Inteliboi Should push his stuff to master at one point tbh
