### ISSUE TITLE
Unable to Login to my Bot

### ISSUE THREAD

**Issue by TBSXeno** [EndlessHosting/Discord-LiveBot#17]
Hello,

Whenever I try to input my bot's token and press either "enter" or "connect," nothing happens. Do you know if there's any way to fix this and if this is either an internal issue or just user error?

Thanks,

Xeno

**Comment by codepupper** [comment]
Please use the Dev branch! It should work!

**Comment by TBSXeno** [comment]
Oh, sick, it works, but now all I see is my server icon on the left, my bot and their ID at the bottom, and the confused kiwi.

**Comment by marens101** [comment]
@TBSXeno That sounds like you're logged in but haven't selected a channel. Click your server icon to see channels, and click a channel to open it.. Settings aren't really a thing right now (apart from username, presence and game), but they may be introduced later. LiveBot is currently only for viewing/sending messages.

**Comment by TBSXeno** [comment]
No, that's the thing: I don't see any channels even when I click on my server.

**Comment by codepupper** [comment]
Does your Bot have Admin Perms?

**Comment by TBSXeno** [comment]
@codepupper Mmhm. The perm integer is 8.

**Comment by TBSXeno** [comment]
I've tried everything I can: make different bots, different permissions, giving them roles with admin permissions, etcetera, but nothing's working - still no channels with the confused kiwi where messages should be.

**Comment by TBSXeno** [comment]
Oh, hey, I can talk now, but there's a problem: I can't talk in any channels that are in categories, no matter how many permissions I give to my bot. I don't know if this is a universal problem or a user problem.

**Comment by TrevorIsanguard** [comment]
What is Dev Branch that you refer to the original user. no clue how to find that or use it

**Comment by iscuck** [comment]
@TrevorIsanguard https://github.com/EndlessHosting/Discord-LiveBot/tree/dev

**Comment by TheBigerGamer** [comment]
It worked for me.
