### ISSUE TITLE
Running NPM Install Git Fail

### ISSUE THREAD

**Issue by justanothernoob4648** [EndlessHosting/Discord-LiveBot#20]
npm ERR! code 1
npm ERR! Command failed: git checkout 11.3-dev
npm ERR! error: pathspec '11.3-dev' did not match any file(s) known to git
npm ERR!
This came up running npm install. I tried running just npm install electron and running the script, but I can't enter my token.

**Comment by SebOuellette** [comment]
It seems like this fork isn't being developed anymore, cause it's severely outdated. You might be interested in checking out the [main repo](https://github.com/SebOuellette/LiveBot)

**Comment by Electromaster232** [comment]
Yeah, this was a little pet project of ours but the developers have moved on. I'll archive this repository.
